### ISSUE TITLE
Refactor names of consumer to remove underscode separators whiting operation names

### ISSUE THREAD

**Issue by georgeslabreche** [tanagraspace/ccsdsmo-malc-sepp-apps#36]
## Todo
- [x] mc_parameter_get_value_consumer --> mc_parameter_getvalue_consumer
- [x] mc_parameter_set_value_consumer --> mc_parameter_setvalue_consumer
- [x] mc_parameter_list_definition_consumer --> mc_parameter_listdefinition_consumer
- [x] sm_appslauncher_list_app_consumer --> sm_appslauncher_listapp_consumer 
- [x] common_directory_lookup_provider_consumer --> common_directory_lookupprovider_consumer

## Motivation
- Nomenclature consistency with the generated areas code.
- Rename confusing function names, e.g.: 
  - mc_parameter_set_value_consumer_set_field_param_value_list --> mc_parameter_setvalue_consumer_set_field_param_value_list
  - mc_parameter_set_value_consumer_get_field_param_value_list --> mc_parameter_setvalue_consumer_get_field_param_value_list
